dataset={
            "Aika" : {"Ada Apa dengan Cinta 2": 3,
                            "Gundala": 5,
                            "Dilan 1991": 4,
                            "Bumi Manusia": 4,
                            "Dua Garis Biru": 4,
                            "Avengers: End Game": 0,
                            "The Lion King": 0,
                            "Aladdin": 0,
                            "Spiderman: Far From Home": 0,
                            "Captain Marvel": 0
                      },

            "Bika" : {"Ada Apa dengan Cinta 2": 0,
                            "Gundala": 0,
                            "Dilan 1991": 0,
                            "Bumi Manusia": 0,
                            "Dua Garis Biru": 0,
                            "Avengers: End Game": 5,
                            "The Lion King": 5,
                            "Aladdin": 0,
                            "Spiderman: Far From Home": 4,
                            "Captain Marvel": 2
                                 },

            "Cika" : {"Ada Apa dengan Cinta 2": 0,
                            "Gundala": 0,
                            "Dilan 1991": 0,
                            "Bumi Manusia": 0,
                            "Dua Garis Biru": 0,
                            "Avengers: End Game": 3,
                            "The Lion King": 0,
                            "Aladdin": 0,
                            "Spiderman: Far From Home": 0,
                            "Captain Marvel": 4
                               },
    
            "Dika" : {"Ada Apa dengan Cinta 2": 4,
                            "Gundala": 4,
                            "Dilan 1991": 4,
                            "Bumi Manusia": 5,
                            "Dua Garis Biru": 3,
                            "Avengers: End Game": 5,
                            "The Lion King": 4,
                            "Aladdin": 5,
                            "Spiderman: Far From Home": 4,
                            "Captain Marvel": 4
                         },

            "Eika" : {"Ada Apa dengan Cinta 2": 3,
                            "Gundala": 0,
                            "Dilan 1991": 2,
                            "Bumi Manusia": 0,
                            "Dua Garis Biru": 5,
                            "Avengers: End Game": 5,
                            "The Lion King": 0,
                            "Aladdin": 1,
                            "Spiderman: Far From Home": 5,
                            "Captain Marvel": 5
                         },

            "Fika" : {"Ada Apa dengan Cinta 2": 0,
                            "Gundala": 0,
                            "Dilan 1991": 0,
                            "Bumi Manusia": 0,
                            "Dua Garis Biru": 0,
                            "Avengers: End Game": 4,
                            "The Lion King": 2,
                            "Aladdin": 5,
                            "Spiderman: Far From Home": 4,
                            "Captain Marvel": 3
                      },

            "Gika" : {"Ada Apa dengan Cinta 2": 5,
                            "Gundala": 4,
                            "Dilan 1991": 3,
                            "Bumi Manusia": 0,
                            "Dua Garis Biru": 0,
                            "Avengers: End Game": 5,
                            "The Lion King": 0,
                            "Aladdin": 5,
                            "Spiderman: Far From Home": 4,
                            "Captain Marvel": 4
                       },

            "Hika" : {"Ada Apa dengan Cinta 2": 3,
                            "Gundala": 0,
                            "Dilan 1991": 5,
                            "Bumi Manusia": 5,
                            "Dua Garis Biru": 4,
                            "Avengers: End Game": 5,
                            "The Lion King": 0,
                            "Aladdin": 0,
                            "Spiderman: Far From Home": 0,
                            "Captain Marvel": 0
                       },

            "Iika" : {"Ada Apa dengan Cinta 2": 5,
                            "Gundala": 4,
                            "Dilan 1991": 4,
                            "Bumi Manusia": 0,
                            "Dua Garis Biru": 0,
                            "Avengers: End Game": 5,
                            "The Lion King": 0,
                            "Aladdin": 0,
                            "Spiderman: Far From Home": 5,
                            "Captain Marvel": 5
                    },

    
            "Jika" : {"Ada Apa dengan Cinta 2": 4,
                            "Gundala": 3,
                            "Dilan 1991": 2,
                            "Bumi Manusia": 4,
                            "Dua Garis Biru": 3,
                            "Avengers: End Game": 5,
                            "The Lion King": 0,
                            "Aladdin": 0,
                            "Spiderman: Far From Home": 4,
                            "Captain Marvel": 3
                            },

            "Kika" : {"Ada Apa dengan Cinta 2": 4,
                            "Gundala": 3,
                            "Dilan 1991": 3,
                            "Bumi Manusia": 0,
                            "Dua Garis Biru": 0,
                            "Avengers: End Game": 5,
                            "The Lion King": 5,
                            "Aladdin": 5,
                            "Spiderman: Far From Home": 4,
                            "Captain Marvel": 5
                                   },

            "Lila" : {"Ada Apa dengan Cinta 2": 5,
                            "Gundala": 0,
                            "Dilan 1991": 5,
                            "Bumi Manusia": 0,
                            "Dua Garis Biru": 0,
                            "Avengers: End Game": 0,
                            "The Lion King": 0,
                            "Aladdin": 0,
                            "Spiderman: Far From Home": 0,
                            "Captain Marvel": 0
                          },

            "Mika" : {"Ada Apa dengan Cinta 2": 4,
                            "Gundala": 0,
                            "Dilan 1991": 4,
                            "Bumi Manusia": 5,
                            "Dua Garis Biru": 0,
                            "Avengers: End Game": 0,
                            "The Lion King": 0,
                            "Aladdin": 4,
                            "Spiderman: Far From Home": 3,
                            "Captain Marvel": 4
                    },

            "Nika" : {"Ada Apa dengan Cinta 2": 5,
                            "Gundala": 5,
                            "Dilan 1991": 5,
                            "Bumi Manusia": 4,
                            "Dua Garis Biru": 3,
                            "Avengers: End Game": 5,
                            "The Lion King": 4,
                            "Aladdin": 5,
                            "Spiderman: Far From Home": 5,
                            "Captain Marvel": 5
                     },

            "Oika" : {"Ada Apa dengan Cinta 2": 0,
                            "Gundala": 4,
                            "Dilan 1991": 4,
                            "Bumi Manusia": 0,
                            "Dua Garis Biru": 0,
                            "Avengers: End Game": 5,
                            "The Lion King": 5,
                            "Aladdin": 5,
                            "Spiderman: Far From Home": 5,
                            "Captain Marvel": 5
                      },

            "Pika" : {"Ada Apa dengan Cinta 2": 2,
                            "Gundala": 4,
                            "Dilan 1991": 3,
                            "Bumi Manusia": 0,
                            "Dua Garis Biru": 5,
                            "Avengers: End Game": 5,
                            "The Lion King": 4,
                            "Aladdin": 5,
                            "Spiderman: Far From Home": 5,
                            "Captain Marvel": 4
                          },

            "Qika" : {"Ada Apa dengan Cinta 2": 4,
                            "Gundala": 3,
                            "Dilan 1991": 4,
                            "Bumi Manusia": 0,
                            "Dua Garis Biru": 0,
                            "Avengers: End Game": 5,
                            "The Lion King": 0,
                            "Aladdin": 5,
                            "Spiderman: Far From Home": 5,
                            "Captain Marvel": 4
                                          },

            "Rika" : {"Ada Apa dengan Cinta 2": 4,
                            "Gundala": 4,
                            "Dilan 1991": 0,
                            "Bumi Manusia": 0,
                            "Dua Garis Biru": 0,
                            "Avengers: End Game": 5,
                            "The Lion King": 5,
                            "Aladdin": 5,
                            "Spiderman: Far From Home": 0,
                            "Captain Marvel": 5
                     },

            "Sika" : {"Ada Apa dengan Cinta 2": 4,
                            "Gundala": 0,
                            "Dilan 1991": 0,
                            "Bumi Manusia": 0,
                            "Dua Garis Biru": 4,
                            "Avengers: End Game": 5,
                            "The Lion King": 5,
                            "Aladdin": 5,
                            "Spiderman: Far From Home": 5,
                            "Captain Marvel": 5
                             },

             "Tika" : {"Ada Apa dengan Cinta 2": 0,
                            "Gundala": 5,
                            "Dilan 1991": 0,
                            "Bumi Manusia": 0,
                            "Dua Garis Biru": 0,
                            "Avengers: End Game": 0,
                            "The Lion King": 0,
                            "Aladdin": 0,
                            "Spiderman: Far From Home": 0,
                            "Captain Marvel": 0
                               },
            
             "Uika" : {"Ada Apa dengan Cinta 2": 5,
                            "Gundala": 0,
                            "Dilan 1991": 0,
                            "Bumi Manusia": 0,
                            "Dua Garis Biru": 0,
                            "Avengers: End Game": 5,
                            "The Lion King": 0,
                            "Aladdin": 0,
                            "Spiderman: Far From Home": 5,
                            "Captain Marvel": 0
                                  },
             "Vika" : {"Ada Apa dengan Cinta 2": 0,
                            "Gundala": 3,
                            "Dilan 1991": 0,
                            "Bumi Manusia": 0,
                            "Dua Garis Biru": 3,
                            "Avengers: End Game": 3,
                            "The Lion King": 3,
                            "Aladdin": 3,
                            "Spiderman: Far From Home": 3,
                            "Captain Marvel": 3
                     },

             "Wika" : {"Ada Apa dengan Cinta 2": 3,
                            "Gundala": 0,
                            "Dilan 1991": 0,
                            "Bumi Manusia": 0,
                            "Dua Garis Biru": 0,
                            "Avengers: End Game": 4,
                            "The Lion King": 0,
                            "Aladdin": 0,
                            "Spiderman: Far From Home": 0,
                            "Captain Marvel": 2
                      },

             "Xika" : {"Ada Apa dengan Cinta 2": 0,
                            "Gundala": 0,
                            "Dilan 1991": 0,
                            "Bumi Manusia": 0,
                            "Dua Garis Biru": 0,
                            "Avengers: End Game": 0,
                            "The Lion King": 5,
                            "Aladdin": 4,
                            "Spiderman: Far From Home": 0,
                            "Captain Marvel": 0
                          }
}